# Generated by Django 3.0.2 on 2020-02-04 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_contact_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
